
<table style="valign:bottom">
<tr>
	<td class="menuprefooter"></td>
</tr>
<tr>
	<td class="menuspacer"></td>
</tr>
<tr>
	<td class="menufooter"></td>
</tr>
</table>

<div class="footer">Design made by <a href="mailto:elmuerte@drunksnipers.com" class="footer">Michiel 'El Muerte' Hendriks</a>, based on the FungKuFull theme for PHP-Nuke.<br />
<a href="http://www.unrealadmin.org" class="footer">The Unreal Admin Page</a> logo used with permission, other images are original</div>

<br />&nbsp;
</body>
</html>
